name: coffee_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ^3.5.1

dependencies:
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  comment_box: ^0.0.18
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.2
  flutter_email_sender: ^6.0.3
  camera_android_camerax: ^0.6.10
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  path: ^1.9.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  cross_file_image: ^1.1.0
  json_annotation: ^4.9.0
  flutter_rating: ^2.0.2
  #firebase_auth: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  logger: ^2.4.0


flutter:
  fonts:
    - family: seaweed
      fonts:
        - asset: assets/fonts/seaweed_script_regular.ttf

  uses-material-design: true

  assets:
    - assets/images/menu/
    - assets/saves/
    - assets/images/icons/

flutter_native_splash:
  color: "#C7A486"
  image: assets/images/icons/app_icon.png
  android_12: 
    image: assets/images/icons/app_icon.png

